### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by eiffelbastin** [Yuseung-Na/pcd2bin#6]
![160804207-733bbdfe-e960-4f7e-9126-e55ad78a1ef2](https://user-images.githubusercontent.com/83037376/161203039-1d7f907f-528b-419f-90b4-07a67a87f953.jpg)

hi,
can u help me solve this error

Thanks in advance ;)

**Comment by Yuseung-Na** [comment]
Did you edit the code from "from tqdm import tqdm" to "import tqdm"??

**Comment by eiffelbastin** [comment]
tried both.

with "import tqdm" I'm getting `Finish to load point clouds! Finish to generate csv meta file Converting Start! 0%| | 0/1 [00:00<?, ?it/s] Traceback (most recent call last): File "pcd2bin.py", line 112, in <module> main() File "pcd2bin.py", line 84, in main pc = pypcd.PointCloud.from_path(pcd_file) AttributeError: module 'pypcd' has no attribute 'PointCloud'`  (installed pypcd using gethub cloning)

with just "import tqdm" I'm getting this 'TypeError: 'module' object is not callable'

**Comment by Yuseung-Na** [comment]
Yes, If you just "import tqdm", then you have to edit "for pcd_file in tqdm(pcd_files):" to "for pcd_file in tqdm.tqdm(pcd_files):".

Anyway, module 'pypcd' currently not work with my code.
I'm currently trying to update it.
